services:
  product-service:
    build: ./product
    image: product-service
    pull_policy: never
    container_name: product-service
    volumes:
      - type: bind
        source: ./product/logs
        target: /app/logs
    networks:
      - backend
    env_file:
      - ./product/.env
    ports:
      - 5001:5001
  cart-service:
    build: ./cart
    image: cart-service
    pull_policy: never
    container_name: cart-service
    volumes:
      - type: bind
        source: ./cart/logs
        target: /app/logs
    networks:
      - backend
    env_file:
      - ./cart/.env
    ports:
      - 5003:5003
  api-gateway:
    depends_on:
      - product-service
      - cart-service
    build: ./api-gateway
    image: api-gateway
    pull_policy: never
    container_name: api-gateway
    volumes:
      - type: bind
        source: ./api-gateway/logs
        target: /app/logs
    networks:
      - backend
    env_file:
      - ./api-gateway/.env
    ports:
      - 5000:5000
  frontend:
    env_file:
      - ./mygrocery/.env
    build: ./mygrocery
    image: mygrocery
    pull_policy: never
    container_name: mygrocery
    ports:
      - 3000:3000

networks:
  backend:
    driver: bridge